# Data Wrangling
## Step 0 - Data load 

- https://www.kaggle.com/datasets/damienbeneschi/krakow-ta-restaurans-data-raw

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("tripadvisor_restaurants.csv")
df.head()

,Unnamed: 0,Name,City,Cuisine Style,Ranking,Rating,Price Range,Number of Reviews,Reviews,URL_TA,ID_TA
0,0,Martine of Martine's Table,Amsterdam,"['French', 'Dutch', 'European']",1.0,5.0,$$ - $$$,136.0,"[['Just like home', 'A Warm Welcome to Wintry ...",/Restaurant_Review-g188590-d11752080-Reviews-M...,d11752080
1,1,De Silveren Spiegel,Amsterdam,"['Dutch', 'European', 'Vegetarian Friendly', '...",2.0,4.5,$$$$,812.0,"[['Great food and staff', 'just perfect'], ['0...",/Restaurant_Review-g188590-d693419-Reviews-De_...,d693419
2,2,La Rive,Amsterdam,"['Mediterranean', 'French', 'International', '...",3.0,4.5,$$$$,567.0,"[['Satisfaction', 'Delicious old school restau...",/Restaurant_Review-g188590-d696959-Reviews-La_...,d696959
3,3,Vinkeles,Amsterdam,"['French', 'European', 'International', 'Conte...",4.0,5.0,$$$$,564.0,"[['True five star dinner', 'A superb evening o...",/Restaurant_Review-g188590-d1239229-Reviews-Vi...,d1239229
4,4,Librije's Zusje Amsterdam,Amsterdam,"['Dutch', 'European', 'International', 'Vegeta...",5.0,4.5,$$$$,316.0,"[['Best meal.... EVER', 'super food experience...",/Restaurant_Review-g188590-d6864170-Reviews-Li...,d6864170

In [3]:
# Check for Lisbon value

values = df["City"].unique().tolist()
values

['Amsterdam',
 'Athens',
 'Barcelona',
 'Berlin',
 'Bratislava',
 'Brussels',
 'Budapest',
 'Copenhagen',
 'Dublin',
 'Edinburgh',
 'Geneva',
 'Hamburg',
 'Helsinki',
 'Krakow',
 'Lisbon',
 'Ljubljana',
 'London',
 'Luxembourg',
 'Lyon',
 'Madrid',
 'Milan',
 'Munich',
 'Oporto',
 'Oslo',
 'Paris',
 'Prague',
 'Rome',
 'Stockholm',
 'Vienna',
 'Warsaw',
 'Zurich']

In [4]:
# Filter only Lisbon & Check

df_lisbon = df[df["City"].str.lower() == "lisbon"]
df_lisbon.head()

,Unnamed: 0,Name,City,Cuisine Style,Ranking,Rating,Price Range,Number of Reviews,Reviews,URL_TA,ID_TA
41093,0,Estamine Art Food Drink,Lisbon,"['Bar', 'Pub', 'Healthy', 'Brazilian', 'Vegeta...",1.0,5.0,$,327.0,[['Fabulous food and people - book in advance....,/Restaurant_Review-g189158-d8574693-Reviews-Es...,d8574693
41094,1,BA Wine Bar do Bairro Alto,Lisbon,"['Portuguese', 'Wine Bar', 'Gluten Free Options']",2.0,4.5,$$ - $$$,1526.0,[['This place should be required for all trav....,/Restaurant_Review-g189158-d2719569-Reviews-BA...,d2719569
41095,2,La Buvette da Mae d'Agua,Lisbon,"['French', 'Mediterranean', 'Healthy', 'Portug...",3.0,5.0,$$ - $$$,177.0,"[['A little gem in Lisbon', 'Unexpected gastro...",/Restaurant_Review-g189158-d12351853-Reviews-L...,d12351853
41096,3,Ha Tapas no Mercado!!!,Lisbon,"['European', 'Portuguese', 'Soups', 'Mediterra...",4.0,5.0,$,423.0,"[['Lunch', 'Great meal, fantastic value!'], ['...",/Restaurant_Review-g189158-d8626284-Reviews-Ha...,d8626284
41097,4,O Vinhaca Tapas & Vinhos,Lisbon,"['Seafood', 'Mediterranean', 'European', 'Port...",5.0,5.0,$$ - $$$,235.0,"[['What an outstanding evening', 'Paolo makes ...",/Restaurant_Review-g189158-d8317381-Reviews-O_...,d8317381

In [5]:
# Check number of rows and columns

df_lisbon.shape

(3986, 11)

## Step 1 - Select only relevant columns

In [6]:
cols_to_keep = [
    "ID_TA",
    "Name",
    "City",
    "Cuisine Style",
    "Ranking",
    "Rating",
    "Price Range",
    "Number of Reviews",
    "Reviews"
]

df_lisbon = df_lisbon[cols_to_keep]

In [7]:
# Rename for SQL friendliness

df_lisbon = df_lisbon.rename(columns={
    "ID_TA": "restaurant_id",
    "Name": "restaurant_name",
    "Cuisine Style": "cuisine_style",
    "Price Range": "price_range",
    "Number of Reviews": "num_reviews"
})

## 2 - Clean cuisine_style

In [8]:
import ast

def parse_cuisine(val):
    if pd.isna(val):
        return []
    try:
        return ast.literal_eval(val)
    except:
        return []

df_lisbon["cuisine_list"] = df_lisbon["cuisine_style"].apply(parse_cuisine)

In [9]:
df_lisbon["primary_cuisine"] = df_lisbon["cuisine_list"].apply(
    lambda x: x[0] if len(x) > 0 else "Unknown"
)

In [10]:
df_lisbon.head()

,restaurant_id,restaurant_name,City,cuisine_style,Ranking,Rating,price_range,num_reviews,Reviews,cuisine_list,primary_cuisine
41093,d8574693,Estamine Art Food Drink,Lisbon,"['Bar', 'Pub', 'Healthy', 'Brazilian', 'Vegeta...",1.0,5.0,$,327.0,[['Fabulous food and people - book in advance....,"[Bar, Pub, Healthy, Brazilian, Vegetarian Frie...",Bar
41094,d2719569,BA Wine Bar do Bairro Alto,Lisbon,"['Portuguese', 'Wine Bar', 'Gluten Free Options']",2.0,4.5,$$ - $$$,1526.0,[['This place should be required for all trav....,"[Portuguese, Wine Bar, Gluten Free Options]",Portuguese
41095,d12351853,La Buvette da Mae d'Agua,Lisbon,"['French', 'Mediterranean', 'Healthy', 'Portug...",3.0,5.0,$$ - $$$,177.0,"[['A little gem in Lisbon', 'Unexpected gastro...","[French, Mediterranean, Healthy, Portuguese, E...",French
41096,d8626284,Ha Tapas no Mercado!!!,Lisbon,"['European', 'Portuguese', 'Soups', 'Mediterra...",4.0,5.0,$,423.0,"[['Lunch', 'Great meal, fantastic value!'], ['...","[European, Portuguese, Soups, Mediterranean, V...",European
41097,d8317381,O Vinhaca Tapas & Vinhos,Lisbon,"['Seafood', 'Mediterranean', 'European', 'Port...",5.0,5.0,$$ - $$$,235.0,"[['What an outstanding evening', 'Paolo makes ...","[Seafood, Mediterranean, European, Portuguese,...",Seafood

## Step 3 - Clean numeric quality fields

In [11]:
# Ranking

df_lisbon["ranking"] = pd.to_numeric(
    df_lisbon["Ranking"], errors="coerce"
)

In [12]:
# Rating

df_lisbon["rating"] = pd.to_numeric(
    df_lisbon["Rating"], errors="coerce"
)

In [13]:
# Number of reviews

df_lisbon["num_reviews"] = pd.to_numeric(
    df_lisbon["num_reviews"], errors="coerce"
)

In [14]:
# Check missing values

df_lisbon[["ranking", "rating", "num_reviews"]].isna().mean()

ranking        0.068490
rating         0.068741
num_reviews    0.130457
dtype: float64

## Step 4 - Normalize price_range

In [15]:
price_map = {
    "$": 1,
    "$$": 2,
    "$$$": 3,
    "$$$$": 4
}

df_lisbon["price_level"] = df_lisbon["price_range"].map(price_map)

In [16]:
# Fill missing price as median 

df_lisbon["price_level"] = df_lisbon["price_level"].fillna(
    df_lisbon["price_level"].median()
)

## Step 5 - Handle missing values

In [17]:
# Handle missing values 

df_lisbon["rating"] = df_lisbon["rating"].fillna(df_lisbon["rating"].median())
df_lisbon["num_reviews"] = df_lisbon["num_reviews"].fillna(0)
df_lisbon["ranking"] = df_lisbon["ranking"].fillna(
    df_lisbon["ranking"].max()
)

## Step 6 - Create normalized popularity signals
- Features that we will use later in the Demand Pressure Index

In [18]:
# Log-transform reviews 

df_lisbon["log_reviews"] = np.log1p(df_lisbon["num_reviews"])

In [19]:
# Normalize ranking

df_lisbon["inv_ranking"] = 1 / df_lisbon["ranking"]

In [20]:
# Normalize (0-1 scale)

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df_lisbon[[
    "rating_norm",
    "reviews_norm",
    "ranking_norm"
]] = scaler.fit_transform(df_lisbon[[
    "rating",
    "log_reviews",
    "inv_ranking"
]])

## Step 7 - Create a Restaurant Popularity Score

In [21]:
df_lisbon["popularity_score"] = (
    0.4 * df_lisbon["reviews_norm"] +
    0.3 * df_lisbon["rating_norm"] +
    0.3 * df_lisbon["ranking_norm"]
)

## Step 8 - Final clean table (Ready for SQL)

In [22]:
restaurants_lisbon = df_lisbon[[
    "restaurant_id",
    "restaurant_name",
    "City",
    "primary_cuisine",
    "price_level",
    "rating",
    "num_reviews",
    "ranking",
    "popularity_score"
]]

In [23]:
restaurants_lisbon.describe()

       price_level       rating  num_reviews      ranking  popularity_score
count  3986.000000  3986.000000  3986.000000  3986.000000      3.986000e+03
mean      1.082037     4.048545   114.219769  1985.549674      3.687040e-01
std       0.489327     0.622327   301.047539  1137.177788      9.829224e-02
min       1.000000     1.000000     0.000000     1.000000      2.172550e-08
25%       1.000000     4.000000     4.000000   997.250000      3.052354e-01
50%       1.000000     4.000000    22.000000  1995.500000      3.721412e-01
75%       1.000000     4.500000    92.000000  2991.750000      4.351887e-01
max       4.000000     5.000000  7560.000000  3717.000000      8.594634e-01

In [24]:
restaurants_lisbon.head()

,restaurant_id,restaurant_name,City,primary_cuisine,price_level,rating,num_reviews,ranking,popularity_score
41093,d8574693,Estamine Art Food Drink,Lisbon,Bar,1.0,5.0,327.0,1.0,0.859463
41094,d2719569,BA Wine Bar do Bairro Alto,Lisbon,Portuguese,1.0,4.5,1526.0,2.0,0.740811
41095,d12351853,La Buvette da Mae d'Agua,Lisbon,French,1.0,5.0,177.0,3.0,0.632033
41096,d8626284,Ha Tapas no Mercado!!!,Lisbon,European,1.0,5.0,423.0,4.0,0.645901
41097,d8317381,O Vinhaca Tapas & Vinhos,Lisbon,Seafood,1.0,5.0,235.0,5.0,0.604655

## 💾 MySQL Connection

In [25]:
#pip install mysql-connector-python sqlalchemy

In [26]:
from sqlalchemy import create_engine
import getpass
import pandas as pd

# Prompt securely for password (input will be hidden)
password = getpass.getpass("MySQL password: ")

db = "restaurant_analytics"
user = "root"
host = "localhost"
port = 3306

connection_string = (
    f"mysql+pymysql://{user}:{password}@{host}:{port}/{db}"
)

engine = create_engine(connection_string)

# Test connection
pd.read_sql("SELECT 1", engine)

MySQL password:  ········

   1
0  1

In [30]:
restaurants_lisbon.to_sql(
    "restaurants_lisbon",
    con=engine,
    if_exists="replace",
    index=False
)

3986

# 📅 Calendar Dimension Table

In [31]:
# base date range

calendar_df = pd.DataFrame({
    "date": pd.date_range(start="2023-01-01", end="2024-12-31", freq="D")
})

In [32]:
calendar_df.head()

        date
0 2023-01-01
1 2023-01-02
2 2023-01-03
3 2023-01-04
4 2023-01-05

In [33]:
calendar_df.tail()

          date
726 2024-12-27
727 2024-12-28
728 2024-12-29
729 2024-12-30
730 2024-12-31

In [34]:
# basic calendar attributes

calendar_df["year"] = calendar_df["date"].dt.year
calendar_df["month"] = calendar_df["date"].dt.month
calendar_df["month_name"] = calendar_df["date"].dt.month_name()
calendar_df["day"] = calendar_df["date"].dt.day
calendar_df["day_of_week"] = calendar_df["date"].dt.weekday  # Monday = 0
calendar_df["day_name"] = calendar_df["date"].dt.day_name()
calendar_df["week_of_year"] = calendar_df["date"].dt.isocalendar().week

In [35]:
# weekend flag

calendar_df["is_weekend"] = calendar_df["day_of_week"].isin([5, 6]).astype(int)

In [36]:
# pip install holidays

In [37]:
# portugal holidays for 2023-2024

import holidays

pt_holidays = holidays.Portugal(years=[2023, 2024])

In [38]:
# holiday flags & names

calendar_df["is_holiday"] = calendar_df["date"].isin(pt_holidays).astype(int)

calendar_df["holiday_name"] = calendar_df["date"].map(
    lambda x: pt_holidays.get(x)
)

/var/folders/6p/v1z8hsjn4rgggm7qtz1wkbyr0000gn/T/ipykernel_1511/1568890671.py:3: FutureWarning: The behavior of 'isin' with dtype=datetime64[ns] and castable values (e.g. strings) is deprecated. In a future version, these will not be considered matching by isin. Explicitly cast to the appropriate dtype before calling isin instead.
  calendar_df["is_holiday"] = calendar_df["date"].isin(pt_holidays).astype(int)

In [39]:
calendar_df[calendar_df["is_holiday"] == 1].head(10)

,date,year,month,month_name,day,day_of_week,day_name,week_of_year,is_weekend,is_holiday,holiday_name
0,2023-01-01,2023,1,January,1,6,Sunday,52,1,1,Ano Novo
96,2023-04-07,2023,4,April,7,4,Friday,14,0,1,Sexta-feira Santa
98,2023-04-09,2023,4,April,9,6,Sunday,14,1,1,Páscoa
114,2023-04-25,2023,4,April,25,1,Tuesday,17,0,1,Dia da Liberdade
120,2023-05-01,2023,5,May,1,0,Monday,18,0,1,Dia do Trabalhador
158,2023-06-08,2023,6,June,8,3,Thursday,23,0,1,Corpo de Deus
160,2023-06-10,2023,6,June,10,5,Saturday,23,1,1,"Dia de Portugal, de Camões e das Comunidades P..."
226,2023-08-15,2023,8,August,15,1,Tuesday,33,0,1,Assunção de Nossa Senhora
277,2023-10-05,2023,10,October,5,3,Thursday,40,0,1,Implantação da República
304,2023-11-01,2023,11,November,1,2,Wednesday,44,0,1,Dia de Todos os Santos

In [40]:
# friday / saturday indicator 

calendar_df["is_fri_sat"] = calendar_df["day_name"].isin(
    ["Friday", "Saturday"]
).astype(int)

In [41]:
# month start / end

calendar_df["is_month_start"] = calendar_df["date"].dt.is_month_start.astype(int)
calendar_df["is_month_end"] = calendar_df["date"].dt.is_month_end.astype(int)

In [42]:
# season 

def get_season(month):
    if month in [12, 1, 2]:
        return "Winter"
    elif month in [3, 4, 5]:
        return "Spring"
    elif month in [6, 7, 8]:
        return "Summer"
    else:
        return "Autumn"

calendar_df["season"] = calendar_df["month"].apply(get_season)

In [43]:
# final calendar_dim structure

calendar_dim = calendar_df[[
    "date",
    "year",
    "month",
    "month_name",
    "day",
    "day_of_week",
    "day_name",
    "week_of_year",
    "season",
    "is_weekend",
    "is_fri_sat",
    "is_holiday",
    "holiday_name"
]]

In [44]:
calendar_dim.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          731 non-null    datetime64[ns]
 1   year          731 non-null    int32
 2   month         731 non-null    int32
 3   month_name    731 non-null    object
 4   day           731 non-null    int32
 5   day_of_week   731 non-null    int32
 6   day_name      731 non-null    object
 7   week_of_year  731 non-null    UInt32
 8   season        731 non-null    object
 9   is_weekend    731 non-null    int64
 10  is_fri_sat    731 non-null    int64
 11  is_holiday    731 non-null    int64
 12  holiday_name  26 non-null     object
dtypes: UInt32(1), datetime64[ns](1), int32(4), int64(3), object(4)
memory usage: 60.8+ KB

In [45]:
calendar_dim.head()

,date,year,month,month_name,day,day_of_week,day_name,week_of_year,season,is_weekend,is_fri_sat,is_holiday,holiday_name
0,2023-01-01,2023,1,January,1,6,Sunday,52,Winter,1,0,1,Ano Novo
1,2023-01-02,2023,1,January,2,0,Monday,1,Winter,0,0,0,None
2,2023-01-03,2023,1,January,3,1,Tuesday,1,Winter,0,0,0,None
3,2023-01-04,2023,1,January,4,2,Wednesday,1,Winter,0,0,0,None
4,2023-01-05,2023,1,January,5,3,Thursday,1,Winter,0,0,0,None

In [46]:
# Save to SQL

calendar_dim.to_sql(
    "calendar_dim",
    con=engine,
    if_exists="replace",
    index=False
)

731

# 🌦️ Weather Data Integration (Lisbon)

Latitude: 38.7223
Longitude: -9.1393

In [47]:
# fetch weather data via API

import requests

In [48]:
url = "https://archive-api.open-meteo.com/v1/archive"

params = {
    "latitude": 38.7223,
    "longitude": -9.1393,
    "start_date": "2023-01-01",
    "end_date": "2024-12-31",
    "daily": [
        "temperature_2m_mean",
        "temperature_2m_min",
        "temperature_2m_max",
        "precipitation_sum"
    ],
    "timezone": "Europe/Lisbon"
}

response = requests.get(url, params=params)
data = response.json()

In [49]:
# convert JSON -> DataFrame

weather_daily = pd.DataFrame({
    "date": data["daily"]["time"],
    "temp_avg": data["daily"]["temperature_2m_mean"],
    "temp_min": data["daily"]["temperature_2m_min"],
    "temp_max": data["daily"]["temperature_2m_max"],
    "precip_mm": data["daily"]["precipitation_sum"]
})

weather_daily["date"] = pd.to_datetime(weather_daily["date"])

In [50]:
# quality checks

weather_daily.head()

        date  temp_avg  temp_min  temp_max  precip_mm
0 2023-01-01      16.1      11.8      18.5       18.4
1 2023-01-02      11.6       8.6      15.3        0.1
2 2023-01-03      10.7       7.2      14.9        0.0
3 2023-01-04      10.7       7.8      14.4        0.0
4 2023-01-05      10.6       8.2      14.2        0.0

In [51]:
weather_daily.tail()

          date  temp_avg  temp_min  temp_max  precip_mm
726 2024-12-27      11.4       8.6      14.7        0.0
727 2024-12-28      11.1       8.1      14.4        0.0
728 2024-12-29      10.2       7.3      13.6        0.0
729 2024-12-30       9.5       6.6      13.1        0.0
730 2024-12-31       9.9       7.1      13.3        0.0

In [52]:
weather_daily.isna().sum()

date         0
temp_avg     0
temp_min     0
temp_max     0
precip_mm    0
dtype: int64

In [53]:
weather_daily.describe()

                      date    temp_avg    temp_min    temp_max   precip_mm
count                  731  731.000000  731.000000  731.000000  731.000000
mean   2024-01-01 00:00:00   17.419152   13.800410   22.042408    1.447880
min    2023-01-01 00:00:00    7.800000    3.500000   10.400000    0.000000
25%    2023-07-02 12:00:00   14.100000   10.850000   17.600000    0.000000
50%    2024-01-01 00:00:00   17.800000   14.400000   21.700000    0.000000
75%    2024-07-01 12:00:00   20.900000   17.000000   26.100000    0.600000
max    2024-12-31 00:00:00   29.900000   25.000000   39.300000   39.800000
std                    NaN    4.426924    3.969795    5.716442    4.307974

In [54]:
# add restaurant-relevant weather flags

weather_daily["is_rainy"] = (weather_daily["precip_mm"] > 1).astype(int)
weather_daily["is_hot"] = (weather_daily["temp_avg"] >= 25).astype(int)
weather_daily["is_cold"] = (weather_daily["temp_avg"] <= 10).astype(int)

In [55]:
weather_daily = weather_daily[[
    "date",
    "temp_avg",
    "temp_min",
    "temp_max",
    "precip_mm",
    "is_rainy",
    "is_hot",
    "is_cold"
]]
weather_daily

,date,temp_avg,temp_min,temp_max,precip_mm,is_rainy,is_hot,is_cold
0,2023-01-01,16.1,11.8,18.5,18.4,1,0,0
1,2023-01-02,11.6,8.6,15.3,0.1,0,0,0
2,2023-01-03,10.7,7.2,14.9,0.0,0,0,0
3,2023-01-04,10.7,7.8,14.4,0.0,0,0,0
4,2023-01-05,10.6,8.2,14.2,0.0,0,0,0
...,...,...,...,...,...,...,...,...
726,2024-12-27,11.4,8.6,14.7,0.0,0,0,0
727,2024-12-28,11.1,8.1,14.4,0.0,0,0,0
728,2024-12-29,10.2,7.3,13.6,0.0,0,0,0
729,2024-12-30,9.5,6.6,13.1,0.0,0,0,1
730,2024-12-31,9.9,7.1,13.3,0.0,0,0,1

In [56]:
# Save to SQL

weather_daily.to_sql(
    "weather_daily",
    con=engine,
    if_exists="replace",
    index=False
)

731

## 📊 Aggregating Monthly Tourism Files into One Dataset

2023 - https://dados.cm-lisboa.pt/dataset/taxa-de-ocupacao-hoteleira-por-amostragem/resource/7f49df91-25aa-4ee9-b951-38e497125e42?inner_span=True

2024 - https://dados.cm-lisboa.pt/dataset/taxa-de-ocupacao-hoteleira-por-amostragem/resource/253f05db-e16e-4648-b526-e0ca438f491d?inner_span=True

In [70]:
hotels_test = pd.read_excel("01_taxa_de_ocupacao_hoteleira_janeiro_2023.xlsx", header=None)
hotels_test.head(15)

                                  0           1         2         3         4
0                               NaN         NaN       NaN       NaN       NaN
1   Amostra hotelaria Lisboa Cidade         NaN       NaN       NaN       NaN
2           Taxa de Ocupação Quarto         NaN       NaN       NaN       NaN
3                               NaN         NaN       NaN       NaN       NaN
4                               NaN         NaN      2023      2022      Var%
5                           janeiro  3 estrelas  0.601304  0.248763  1.417172
6                               NaN  4 estrelas  0.526374  0.216203  1.434631
7                               NaN  5 estrelas  0.395702  0.163939  1.413711
8                               NaN       Total  0.499013  0.205821  1.424505
9   Acumulado de janeiro a janeiro   3 estrelas  0.601304  0.248763  1.417172
10                              NaN  4 estrelas  0.526374  0.216203  1.434631
11                              NaN  5 estrelas  0.395702  0.163939  1.413711
12                              NaN       Total  0.499013  0.205821  1.424505
13                              NaN         NaN       NaN       NaN       NaN
14                              NaN         NaN       NaN       NaN       NaN

In [71]:
month_map = {
    "janeiro": 1, "fevereiro": 2, "marco": 3, "abril": 4,
    "maio": 5, "junho": 6, "julho": 7, "agosto": 8,
    "setembro": 9, "outubro": 10, "novembro": 11, "dezembro": 12
}

In [72]:
def load_hotel_occupancy(files):
    rows = []

    for file in files:
        # --- read & basic cleaning ---
        hotels = pd.read_excel(file, skiprows=4)
        hotels = hotels.loc[:, ~hotels.columns.duplicated()]

        hotels = hotels.rename(columns={
            "Unnamed: 0": "month_label",
            "Unnamed: 1": "category"
        })

        hotels["category"] = hotels["category"].astype(str).str.strip()

        # --- keep only Total ---
        hotels_total = hotels[hotels["category"].str.lower() == "total"].iloc[[0]].copy()

        # --- parse filename ---
        # example: 01_taxa_de_ocupacao_hoteleira_janeiro_2023.xlsx
        parts = file.replace(".xlsx", "").split("_")
        month_label = parts[-2]
        year = int(parts[-1])

        # --- extract occupancy for the correct year ---
        if year not in hotels_total.columns:
            raise ValueError(f"Year column {year} not found in {file}")

        occupancy = hotels_total[year].iloc[0]

        # --- build row ---
        row = {
            "year": year,
            "month_label": month_label,
            "month_num": month_map[month_label],
            "category": "Total",
            "occupancy": occupancy,
            "source_file": file
        }

        rows.append(row)

    hotels_final = pd.DataFrame(rows)

    # --- build date ---
    hotels_final["date"] = pd.to_datetime(
        dict(
            year=hotels_final["year"],
            month=hotels_final["month_num"],
            day=1
        )
    )

    return hotels_final.sort_values("date").reset_index(drop=True)

In [73]:
def validate_12_months(hotels):
    counts = hotels.groupby("year")["month_num"].nunique()

    bad_years = counts[counts != 12]

    if not bad_years.empty:
        raise ValueError(
            f"Month validation failed:\n{bad_years}"
        )

    print("Validation passed: each year has 12 months")

In [75]:
files = [
    "01_taxa_de_ocupacao_hoteleira_janeiro_2023.xlsx",
    "02_taxa_de_ocupacao_hoteleira_fevereiro_2023.xlsx",
    "03_taxa_de_ocupacao_hoteleira_marco_2023.xlsx",
    "04_taxa_de_ocupacao_hoteleira_abril_2023.xlsx",
    "05_taxa_de_ocupacao_hoteleira_maio_2023.xlsx",
    "06_taxa_de_ocupacao_hoteleira_junho_2023.xlsx",
    "07_taxa_de_ocupacao_hoteleira_julho_2023.xlsx",
    "08_taxa_de_ocupacao_hoteleira_agosto_2023.xlsx",
    "09_taxa_de_ocupacao_hoteleira_setembro_2023.xlsx",
    "10_taxa_de_ocupacao_hoteleira_outubro_2023.xlsx",
    "11_taxa_de_ocupacao_hoteleira_novembro_2023.xlsx",
    "12_taxa_de_ocupacao_hoteleira_dezembro_2023.xlsx",
    "01_taxa_de_ocupacao_hoteleira_janeiro_2024.xlsx",
    "02_taxa_de_ocupacao_hoteleira_fevereiro_2024.xlsx",
    "03_taxa_de_ocupacao_hoteleira_marco_2024.xlsx",
    "04_taxa_de_ocupacao_hoteleira_abril_2024.xlsx",
    "05_taxa_de_ocupacao_hoteleira_maio_2024.xlsx",
    "06_taxa_de_ocupacao_hoteleira_junho_2024.xlsx",
    "07_taxa_de_ocupacao_hoteleira_julho_2024.xlsx",
    "08_taxa_de_ocupacao_hoteleira_agosto_2024.xlsx",
    "09_taxa_de_ocupacao_hoteleira_setembro_2024.xlsx",
    "10_taxa_de_ocupacao_hoteleira_outubro_2024.xlsx",
    "11_taxa_de_ocupacao_hoteleira_novembro_2024.xlsx",
    "12_taxa_de_ocupacao_hoteleira_dezembro_2024.xlsx"
]


hotels = load_hotel_occupancy(files)
validate_12_months(hotels)

Validation passed: each year has 12 months

In [76]:
def compute_yoy(hotels):
    hotels = hotels.sort_values("date")

    hotels["yoy"] = (
        hotels
        .set_index("date")
        .groupby("month_num")["occupancy"]
        .pct_change()
        .reset_index(drop=True)
    )

    return hotels

In [77]:
hotels = compute_yoy(hotels)

In [78]:
hotels

,year,month_label,month_num,category,occupancy,source_file,date,yoy
0,2023,janeiro,1,Total,0.499013,01_taxa_de_ocupacao_hoteleira_janeiro_2023.xlsx,2023-01-01,NaN
1,2023,fevereiro,2,Total,0.605424,02_taxa_de_ocupacao_hoteleira_fevereiro_2023.xlsx,2023-02-01,NaN
2,2023,marco,3,Total,0.725233,03_taxa_de_ocupacao_hoteleira_marco_2023.xlsx,2023-03-01,NaN
3,2023,abril,4,Total,0.803010,04_taxa_de_ocupacao_hoteleira_abril_2023.xlsx,2023-04-01,NaN
4,2023,maio,5,Total,0.871726,05_taxa_de_ocupacao_hoteleira_maio_2023.xlsx,2023-05-01,NaN
5,2023,junho,6,Total,0.820553,06_taxa_de_ocupacao_hoteleira_junho_2023.xlsx,2023-06-01,NaN
6,2023,julho,7,Total,0.779120,07_taxa_de_ocupacao_hoteleira_julho_2023.xlsx,2023-07-01,NaN
7,2023,agosto,8,Total,0.797907,08_taxa_de_ocupacao_hoteleira_agosto_2023.xlsx,2023-08-01,NaN
8,2023,setembro,9,Total,0.883214,09_taxa_de_ocupacao_hoteleira_setembro_2023.xlsx,2023-09-01,NaN
9,2023,outubro,10,Total,0.856799,10_taxa_de_ocupacao_hoteleira_outubro_2023.xlsx,2023-10-01,NaN
10,2023,novembro,11,Total,0.714521,11_taxa_de_ocupacao_hoteleira_novembro_2023.xlsx,2023-11-01,NaN
11,2023,dezembro,12,Total,0.528593,12_taxa_de_ocupacao_hoteleira_dezembro_2023.xlsx,2023-12-01,NaN
12,2024,janeiro,1,Total,0.480132,01_taxa_de_ocupacao_hoteleira_janeiro_2024.xlsx,2024-01-01,-0.037838
13,2024,fevereiro,2,Total,0.628073,02_taxa_de_ocupacao_hoteleira_fevereiro_2024.xlsx,2024-02-01,0.037411
14,2024,marco,3,Total,0.748034,03_taxa_de_ocupacao_hoteleira_marco_2024.xlsx,2024-03-01,0.031440
15,2024,abril,4,Total,0.810200,04_taxa_de_ocupacao_hoteleira_abril_2024.xlsx,2024-04-01,0.008953
16,2024,maio,5,Total,0.867797,05_taxa_de_ocupacao_hoteleira_maio_2024.xlsx,2024-05-01,-0.004508
17,2024,junho,6,Total,0.839700,06_taxa_de_ocupacao_hoteleira_junho_2024.xlsx,2024-06-01,0.023335
18,2024,julho,7,Total,0.790465,07_taxa_de_ocupacao_hoteleira_julho_2024.xlsx,2024-07-01,0.014562
19,2024,agosto,8,Total,0.810128,08_taxa_de_ocupacao_hoteleira_agosto_2024.xlsx,2024-08-01,0.015316
20,2024,setembro,9,Total,0.902546,09_taxa_de_ocupacao_hoteleira_setembro_2024.xlsx,2024-09-01,0.021888
21,2024,outubro,10,Total,0.877783,10_taxa_de_ocupacao_hoteleira_outubro_2024.xlsx,2024-10-01,0.024492
22,2024,novembro,11,Total,0.755213,11_taxa_de_ocupacao_hoteleira_novembro_2024.xlsx,2024-11-01,0.056950
23,2024,dezembro,12,Total,0.539019,12_taxa_de_ocupacao_hoteleira_dezembro_2024.xlsx,2024-12-01,0.019724

In [79]:
tourism_monthly = hotels.copy()

tourism_monthly = tourism_monthly[[
    "date",
    "year",
    "month_num",
    "occupancy",
    "yoy"
]].rename(columns={
    "month_num": "month",
    "occupancy": "hotel_occupancy_rate",
    "yoy": "occupancy_yoy"
})

tourism_monthly = tourism_monthly.sort_values("date").reset_index(drop=True)

In [80]:
tourism_monthly.head()

        date  year  month  hotel_occupancy_rate  occupancy_yoy
0 2023-01-01  2023      1              0.499013            NaN
1 2023-02-01  2023      2              0.605424            NaN
2 2023-03-01  2023      3              0.725233            NaN
3 2023-04-01  2023      4              0.803010            NaN
4 2023-05-01  2023      5              0.871726            NaN

In [81]:
tourism_monthly.tail()

         date  year  month  hotel_occupancy_rate  occupancy_yoy
19 2024-08-01  2024      8              0.810128       0.015316
20 2024-09-01  2024      9              0.902546       0.021888
21 2024-10-01  2024     10              0.877783       0.024492
22 2024-11-01  2024     11              0.755213       0.056950
23 2024-12-01  2024     12              0.539019       0.019724

In [82]:
tourism_monthly.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   date                  24 non-null     datetime64[ns]
 1   year                  24 non-null     int64
 2   month                 24 non-null     int64
 3   hotel_occupancy_rate  24 non-null     float64
 4   occupancy_yoy         12 non-null     float64
dtypes: datetime64[ns](1), float64(2), int64(2)
memory usage: 1.1 KB

In [83]:
# normalize occupancy across years

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

tourism_monthly["occupancy_norm"] = scaler.fit_transform(
    tourism_monthly[["hotel_occupancy_rate"]]
)

In [84]:
# expand monthly -> daily

daily_dates = pd.DataFrame({
    "date": pd.date_range(
        start="2023-01-01",
        end="2024-12-31",
        freq="D"
    )
})

tourism_daily = (
    daily_dates
    .merge(
        tourism_monthly[[
            "date",
            "hotel_occupancy_rate",
            "occupancy_norm"
        ]],
        on="date",
        how="left"
    )
    .ffill()
)

In [85]:
tourism_daily.head(10)

        date  hotel_occupancy_rate  occupancy_norm
0 2023-01-01              0.499013        0.044699
1 2023-01-02              0.499013        0.044699
2 2023-01-03              0.499013        0.044699
3 2023-01-04              0.499013        0.044699
4 2023-01-05              0.499013        0.044699
5 2023-01-06              0.499013        0.044699
6 2023-01-07              0.499013        0.044699
7 2023-01-08              0.499013        0.044699
8 2023-01-09              0.499013        0.044699
9 2023-01-10              0.499013        0.044699

In [86]:
tourism_daily.tail(10)

          date  hotel_occupancy_rate  occupancy_norm
721 2024-12-22              0.539019        0.139407
722 2024-12-23              0.539019        0.139407
723 2024-12-24              0.539019        0.139407
724 2024-12-25              0.539019        0.139407
725 2024-12-26              0.539019        0.139407
726 2024-12-27              0.539019        0.139407
727 2024-12-28              0.539019        0.139407
728 2024-12-29              0.539019        0.139407
729 2024-12-30              0.539019        0.139407
730 2024-12-31              0.539019        0.139407

In [87]:
tourism_daily.groupby(tourism_daily["date"].dt.year).count()

      date  hotel_occupancy_rate  occupancy_norm
date
2023   365                   365             365
2024   366                   366             366

In [88]:
# Save to SQL

tourism_daily.to_sql(
    "tourism_daily",
    con=engine,
    if_exists="replace",
    index=False
)

731

- Monthly hotel occupancy data for Lisbon for 2023 and 2024 was obtained from the official municipal open data portal. The data was standardized and expanded to daily frequency using forward-fill to enable integration with calendar and weather dimensions. Normalized occupancy indicators were used as a proxy for tourism intensity in the demand pressure analysis.

# 🎯 Demand Pressure Index
- The Demand Pressure Index estimates how intense external demand conditions are for restaurants in Lisbon on a given day, based on tourism intensity, weather conditions, and calendar effects.

In [89]:
# weather score:

weather_daily["weather_score"] = (
    1
    - 0.3 * weather_daily["is_rainy"]
    - 0.2 * weather_daily["is_hot"]
    - 0.1 * weather_daily["is_cold"]
)

weather_daily["weather_score"] = weather_daily["weather_score"].clip(0, 1)

In [90]:
# calendar pressure score:

calendar_dim["calendar_score"] = (
    0.5
    + 0.2 * calendar_dim["is_weekend"]
    + 0.2 * calendar_dim["is_fri_sat"]
    + 0.3 * calendar_dim["is_holiday"]
)

calendar_dim["calendar_score"] = calendar_dim["calendar_score"].clip(0, 1)

/var/folders/6p/v1z8hsjn4rgggm7qtz1wkbyr0000gn/T/ipykernel_1511/2210197323.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  calendar_dim["calendar_score"] = (
/var/folders/6p/v1z8hsjn4rgggm7qtz1wkbyr0000gn/T/ipykernel_1511/2210197323.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  calendar_dim["calendar_score"] = calendar_dim["calendar_score"].clip(0, 1)

In [91]:
# restaurant exposure score

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
restaurants_lisbon["exposure_score"] = scaler.fit_transform(
    restaurants_lisbon[["num_reviews"]]
)

/var/folders/6p/v1z8hsjn4rgggm7qtz1wkbyr0000gn/T/ipykernel_1511/3786851873.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  restaurants_lisbon["exposure_score"] = scaler.fit_transform(

In [92]:
# build the daily demand pressure index

dpi_daily = (
    calendar_dim
    .merge(tourism_daily, on="date", how="left")
    .merge(weather_daily, on="date", how="left")
)

In [93]:
# compute DPI (0-100)

dpi_daily["demand_pressure_index"] = (
    100 * (
        0.4 * dpi_daily["occupancy_norm"]
      + 0.3 * dpi_daily["calendar_score"]
      + 0.3 * dpi_daily["weather_score"]
    )
)

In [94]:
dpi_daily["demand_pressure_index"].describe()

count    731.000000
mean      71.939158
std       13.606204
min       33.000000
25%       62.864349
50%       75.091346
75%       82.081597
max       97.655163
Name: demand_pressure_index, dtype: float64

In [95]:
# Save to SQL

dpi_daily.to_sql(
    "demand_pressure_daily",
    con=engine,
    if_exists="replace",
    index=False
)

731

# SQL views for analysis

In [96]:
from sqlalchemy import create_engine
from sqlalchemy import text

engine

Engine(mysql+pymysql://root:***@localhost:3306/restaurant_analytics)

In [97]:
with engine.connect() as conn:
    result = conn.execute(text("SELECT DATABASE();"))
    print(result.fetchall())

[('restaurant_analytics',)]

In [98]:
create_view_sql = """
CREATE OR REPLACE VIEW vw_daily_demand_context AS
SELECT
    d.date,
    d.demand_pressure_index,

    t.hotel_occupancy_rate,
    t.occupancy_norm,

    w.temp_avg,
    w.precip_mm,
    w.is_rainy,
    w.is_hot,
    w.is_cold,

    c.day_name,
    c.week_of_year,
    c.month,
    c.month_name,
    c.season,
    c.is_weekend,
    c.is_fri_sat,
    c.is_holiday,
    c.holiday_name

FROM demand_pressure_daily d
LEFT JOIN tourism_daily t ON d.date = t.date
LEFT JOIN weather_daily w ON d.date = w.date
LEFT JOIN calendar_dim c ON d.date = c.date;
"""

In [99]:
with engine.begin() as conn:
    conn.exec_driver_sql(create_view_sql)

In [100]:
with engine.connect() as conn:
    result = conn.execute(text("SHOW FULL TABLES WHERE Table_type = 'VIEW';"))
    print(result.fetchall())

[('vw_daily_demand_context', 'VIEW'), ('vw_holiday_vs_nonholiday', 'VIEW'), ('vw_monthly_pressure_summary', 'VIEW'), ('vw_restaurant_exposure', 'VIEW'), ('vw_weather_impact', 'VIEW')]

In [101]:
query = """
SELECT *
FROM vw_daily_demand_context
ORDER BY date
"""

df_daily = pd.read_sql(query, engine)
df_daily.head()

,date,demand_pressure_index,hotel_occupancy_rate,occupancy_norm,temp_avg,precip_mm,is_rainy,is_hot,is_cold,day_name,week_of_year,month,month_name,season,is_weekend,is_fri_sat,is_holiday,holiday_name
0,2023-01-01,52.787975,0.499013,0.044699,16.1,18.4,1,0,0,Sunday,52,1,January,Winter,1,0,1,Ano Novo
1,2023-01-02,46.787975,0.499013,0.044699,11.6,0.1,0,0,0,Monday,1,1,January,Winter,0,0,0,None
2,2023-01-03,46.787975,0.499013,0.044699,10.7,0.0,0,0,0,Tuesday,1,1,January,Winter,0,0,0,None
3,2023-01-04,46.787975,0.499013,0.044699,10.7,0.0,0,0,0,Wednesday,1,1,January,Winter,0,0,0,None
4,2023-01-05,46.787975,0.499013,0.044699,10.6,0.0,0,0,0,Thursday,1,1,January,Winter,0,0,0,None

In [103]:
# ==================================================
# VIEW 1: Daily Demand Context
# ==================================================
vw_daily_demand_context = """
CREATE OR REPLACE VIEW vw_daily_demand_context AS
SELECT
    d.date,
    d.demand_pressure_index,

    -- Tourism
    t.hotel_occupancy_rate,
    t.occupancy_norm,

    -- Weather
    w.temp_avg,
    w.precip_mm,
    w.is_rainy,
    w.is_hot,
    w.is_cold,

    -- Calendar
    c.day_name,
    c.week_of_year,
    c.month,
    c.month_name,
    c.season,
    c.is_weekend,
    c.is_fri_sat,
    c.is_holiday,
    c.holiday_name

FROM demand_pressure_daily d
LEFT JOIN tourism_daily t
    ON d.date = t.date
LEFT JOIN weather_daily w
    ON d.date = w.date
LEFT JOIN calendar_dim c
    ON d.date = c.date;
"""

# ==================================================
# VIEW 2: Monthly Pressure Summary
# ==================================================
vw_monthly_pressure_summary = """
CREATE OR REPLACE VIEW vw_monthly_pressure_summary AS
SELECT
    YEAR(date) AS year,
    MONTH(date) AS month,
    month_name,
    season,

    AVG(demand_pressure_index) AS avg_pressure,
    MAX(demand_pressure_index) AS peak_pressure,
    AVG(hotel_occupancy_rate) AS avg_occupancy,
    AVG(temp_avg) AS avg_temp,
    SUM(is_holiday) AS holiday_days

FROM vw_daily_demand_context
GROUP BY
    YEAR(date),
    MONTH(date),
    month_name,
    season;
"""

# ==================================================
# VIEW 3: Holiday vs Non-Holiday
# ==================================================
vw_holiday_vs_nonholiday = """
CREATE OR REPLACE VIEW vw_holiday_vs_nonholiday AS
SELECT
    CASE
        WHEN is_holiday = 1 THEN 'Holiday'
        ELSE 'Non-Holiday'
    END AS day_type,

    COUNT(*) AS days,
    AVG(demand_pressure_index) AS avg_pressure,
    AVG(hotel_occupancy_rate) AS avg_occupancy,
    AVG(temp_avg) AS avg_temp

FROM vw_daily_demand_context
GROUP BY day_type;
"""

# ==================================================
# VIEW 4: Weather Impact
# ==================================================
vw_weather_impact = """
CREATE OR REPLACE VIEW vw_weather_impact AS
SELECT
    is_rainy,
    is_hot,
    is_cold,

    COUNT(*) AS days,
    AVG(demand_pressure_index) AS avg_pressure,
    AVG(hotel_occupancy_rate) AS avg_occupancy

FROM vw_daily_demand_context
GROUP BY
    is_rainy,
    is_hot,
    is_cold;
"""

# ==================================================
# VIEW 5: Restaurant Exposure (FIXED)
# ==================================================
vw_restaurant_exposure = """
CREATE OR REPLACE VIEW vw_restaurant_exposure AS
SELECT
    r.restaurant_id,
    r.restaurant_name,
    r.City,
    r.primary_cuisine,
    r.price_level,
    r.rating,
    r.num_reviews,
    r.ranking,
    r.popularity_score,

    AVG(d.demand_pressure_index) AS avg_city_pressure,
    MAX(d.demand_pressure_index) AS peak_city_pressure

FROM restaurants_lisbon r
CROSS JOIN demand_pressure_daily d
GROUP BY
    r.restaurant_id,
    r.restaurant_name,
    r.City,
    r.primary_cuisine,
    r.price_level,
    r.rating,
    r.num_reviews,
    r.ranking,
    r.popularity_score;
"""

# ==================================================
# EXECUTE ALL VIEWS
# ==================================================
view_sql_list = [
    vw_daily_demand_context,
    vw_monthly_pressure_summary,
    vw_holiday_vs_nonholiday,
    vw_weather_impact,
    vw_restaurant_exposure
]

with engine.begin() as conn:
    for view_sql in view_sql_list:
        conn.exec_driver_sql(view_sql)

print("All SQL views created successfully.")

All SQL views created successfully.

In [104]:
with engine.connect() as conn:
    result = conn.execute(
        text("SHOW FULL TABLES WHERE Table_type = 'VIEW';")
    )
    for row in result.fetchall():
        print(row)

('vw_daily_demand_context', 'VIEW')
('vw_holiday_vs_nonholiday', 'VIEW')
('vw_monthly_pressure_summary', 'VIEW')
('vw_restaurant_exposure', 'VIEW')
('vw_weather_impact', 'VIEW')

In [105]:
with engine.connect() as conn:
    result = conn.execute(
        text("SHOW FULL TABLES WHERE Table_type = 'VIEW';")
    )
    views = result.fetchall()

for v in views:
    print(v)

('vw_daily_demand_context', 'VIEW')
('vw_holiday_vs_nonholiday', 'VIEW')
('vw_monthly_pressure_summary', 'VIEW')
('vw_restaurant_exposure', 'VIEW')
('vw_weather_impact', 'VIEW')

In [106]:
views = [
    "vw_daily_demand_context",
    "vw_monthly_pressure_summary",
    "vw_holiday_vs_nonholiday",
    "vw_weather_impact",
    "vw_restaurant_exposure"
]

for v in views:
    print(f"\n===== {v} =====")
    df = pd.read_sql(f"SELECT * FROM {v} LIMIT 5", engine)
    display(df)

===== vw_daily_demand_context =====

,date,demand_pressure_index,hotel_occupancy_rate,occupancy_norm,temp_avg,precip_mm,is_rainy,is_hot,is_cold,day_name,week_of_year,month,month_name,season,is_weekend,is_fri_sat,is_holiday,holiday_name
0,2023-01-01,52.787975,0.499013,0.044699,16.1,18.4,1,0,0,Sunday,52,1,January,Winter,1,0,1,Ano Novo
1,2023-01-02,46.787975,0.499013,0.044699,11.6,0.1,0,0,0,Monday,1,1,January,Winter,0,0,0,None
2,2023-01-03,46.787975,0.499013,0.044699,10.7,0.0,0,0,0,Tuesday,1,1,January,Winter,0,0,0,None
3,2023-01-04,46.787975,0.499013,0.044699,10.7,0.0,0,0,0,Wednesday,1,1,January,Winter,0,0,0,None
4,2023-01-05,46.787975,0.499013,0.044699,10.6,0.0,0,0,0,Thursday,1,1,January,Winter,0,0,0,None

===== vw_monthly_pressure_summary =====

,year,month,month_name,season,avg_pressure,peak_pressure,avg_occupancy,avg_temp,holiday_days
0,2023,1,January,Winter,47.755717,58.787975,0.499013,11.574194,1.0
1,2023,2,February,Winter,57.828635,68.864349,0.605424,11.132143,0.0
2,2023,3,March,Spring,69.951465,80.209529,0.725233,14.038710,0.0
3,2023,4,April,Spring,79.674618,90.574618,0.803010,17.696667,3.0
4,2023,5,May,Spring,84.597726,94.081597,0.871726,19.041935,1.0

===== vw_holiday_vs_nonholiday =====

      day_type  days  avg_pressure  avg_occupancy   avg_temp
0      Holiday    26     76.997235       0.722991  16.742308
1  Non-Holiday   705     71.752619       0.748314  17.444113

===== vw_weather_impact =====

   is_rainy  is_hot  is_cold  days  avg_pressure  avg_occupancy
0         1       0        0   139     65.011785       0.746620
1         0       0        0   533     74.981341       0.757218
2         0       0        1    32     52.079101       0.557860
3         1       0        1     4     43.326242       0.557500
4         0       1        0    23     75.912828       0.821734

===== vw_restaurant_exposure =====

,restaurant_id,restaurant_name,City,primary_cuisine,price_level,rating,num_reviews,ranking,popularity_score,avg_city_pressure,peak_city_pressure
0,d8574693,Estamine Art Food Drink,Lisbon,Bar,1.0,5.0,327.0,1.0,0.859463,71.939158,97.655163
1,d2719569,BA Wine Bar do Bairro Alto,Lisbon,Portuguese,1.0,4.5,1526.0,2.0,0.740811,71.939158,97.655163
2,d12351853,La Buvette da Mae d'Agua,Lisbon,French,1.0,5.0,177.0,3.0,0.632033,71.939158,97.655163
3,d8626284,Ha Tapas no Mercado!!!,Lisbon,European,1.0,5.0,423.0,4.0,0.645901,71.939158,97.655163
4,d8317381,O Vinhaca Tapas & Vinhos,Lisbon,Seafood,1.0,5.0,235.0,5.0,0.604655,71.939158,97.655163

In [108]:
views = [
    "vw_daily_demand_context",
    "vw_monthly_pressure_summary",
    "vw_holiday_vs_nonholiday",
    "vw_weather_impact",
    "vw_restaurant_exposure"
]

for v in views:
    df = pd.read_sql(f"SELECT * FROM {v}", engine)
    df.to_csv(f"{v}.csv", index=False)

print("CSV exports completed.")

CSV exports completed.